CREATE TABLE IF NOT EXISTS recomart_features.feature_batch (
    feature_batch_id VARCHAR(80) PRIMARY KEY,
    source_batch_id VARCHAR(100) NOT NULL,
    preparation_run_id UUID NOT NULL,
    feature_reference_timestamp TIMESTAMPTZ NOT NULL,
    feature_source_split VARCHAR(10) NOT NULL CHECK (feature_source_split IN ('train','all')),
    started_at TIMESTAMPTZ NOT NULL,
    completed_at TIMESTAMPTZ,
    status VARCHAR(30) NOT NULL,
    user_feature_count BIGINT DEFAULT 0,
    item_feature_count BIGINT DEFAULT 0,
    user_item_feature_count BIGINT DEFAULT 0,
    cooccurrence_feature_count BIGINT DEFAULT 0,
    similarity_feature_count BIGINT DEFAULT 0,
    configuration_hash CHAR(64) NOT NULL,
    source_checksum CHAR(64) NOT NULL,
    identity_hash CHAR(64) NOT NULL UNIQUE,
    error_message TEXT,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS recomart_features.feature_definition (
    feature_name VARCHAR(150) NOT NULL,
    feature_group VARCHAR(50) NOT NULL,
    entity_type VARCHAR(50) NOT NULL,
    data_type VARCHAR(50) NOT NULL,
    description TEXT NOT NULL,
    calculation_logic TEXT NOT NULL,
    source_columns JSONB NOT NULL,
    default_value TEXT,
    null_handling TEXT NOT NULL,
    feature_version VARCHAR(30) NOT NULL,
    owner VARCHAR(80) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (feature_name, feature_version)
);

CREATE TABLE IF NOT EXISTS recomart_features.feature_lineage (
    lineage_id UUID PRIMARY KEY,
    feature_batch_id VARCHAR(80) NOT NULL REFERENCES recomart_features.feature_batch(feature_batch_id),
    feature_name VARCHAR(150) NOT NULL,
    source_dataset VARCHAR(150) NOT NULL,
    source_columns JSONB NOT NULL,
    transformation_name VARCHAR(150) NOT NULL,
    transformation_version VARCHAR(30) NOT NULL,
    transformation_parameters JSONB NOT NULL,
    source_checksum CHAR(64) NOT NULL,
    output_table VARCHAR(100) NOT NULL,
    generated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS recomart_features.user_features (
    feature_batch_id VARCHAR(80) NOT NULL,
    source_batch_id VARCHAR(100) NOT NULL,
    feature_reference_timestamp TIMESTAMPTZ NOT NULL,
    user_id BIGINT NOT NULL,
    total_interactions BIGINT NOT NULL,
    unique_products_interacted BIGINT NOT NULL,
    view_count BIGINT NOT NULL,
    wishlist_count BIGINT NOT NULL,
    add_to_cart_count BIGINT NOT NULL,
    purchase_count BIGINT NOT NULL,
    interaction_frequency_per_day DOUBLE PRECISION NOT NULL,
    interaction_frequency_last_7d DOUBLE PRECISION NOT NULL,
    interaction_frequency_last_30d DOUBLE PRECISION NOT NULL,
    active_days BIGINT NOT NULL,
    session_count BIGINT NOT NULL,
    average_events_per_session DOUBLE PRECISION,
    average_rating_given DOUBLE PRECISION,
    rating_count BIGINT NOT NULL,
    rating_stddev DOUBLE PRECISION,
    minimum_rating_given DOUBLE PRECISION,
    maximum_rating_given DOUBLE PRECISION,
    total_quantity_purchased DOUBLE PRECISION NOT NULL,
    total_spend DOUBLE PRECISION NOT NULL,
    average_order_value DOUBLE PRECISION,
    maximum_order_value DOUBLE PRECISION,
    days_since_last_interaction DOUBLE PRECISION,
    days_since_last_purchase DOUBLE PRECISION,
    user_tenure_days DOUBLE PRECISION,
    preferred_category TEXT,
    preferred_brand TEXT,
    preferred_interaction_type TEXT,
    view_to_cart_ratio DOUBLE PRECISION,
    cart_to_purchase_ratio DOUBLE PRECISION,
    purchase_conversion_rate DOUBLE PRECISION,
    user_activity_level VARCHAR(10) NOT NULL,
    cold_start_user_flag BOOLEAN NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (feature_batch_id, user_id)
);

CREATE TABLE IF NOT EXISTS recomart_features.item_features (
    feature_batch_id VARCHAR(80) NOT NULL,
    source_batch_id VARCHAR(100) NOT NULL,
    feature_reference_timestamp TIMESTAMPTZ NOT NULL,
    product_id BIGINT NOT NULL,
    total_interactions BIGINT NOT NULL,
    unique_users BIGINT NOT NULL,
    view_count BIGINT NOT NULL,
    wishlist_count BIGINT NOT NULL,
    add_to_cart_count BIGINT NOT NULL,
    purchase_count BIGINT NOT NULL,
    average_rating DOUBLE PRECISION,
    rating_count BIGINT NOT NULL,
    rating_stddev DOUBLE PRECISION,
    minimum_rating DOUBLE PRECISION,
    maximum_rating DOUBLE PRECISION,
    total_quantity_sold DOUBLE PRECISION NOT NULL,
    total_revenue DOUBLE PRECISION NOT NULL,
    average_selling_amount DOUBLE PRECISION,
    interaction_popularity_score DOUBLE PRECISION NOT NULL,
    purchase_popularity_score DOUBLE PRECISION NOT NULL,
    external_popularity_score DOUBLE PRECISION,
    view_to_cart_ratio DOUBLE PRECISION,
    cart_to_purchase_ratio DOUBLE PRECISION,
    purchase_conversion_rate DOUBLE PRECISION,
    interaction_count_last_7d BIGINT NOT NULL,
    interaction_count_last_30d BIGINT NOT NULL,
    popularity_growth_rate DOUBLE PRECISION,
    category TEXT NOT NULL,
    brand TEXT NOT NULL,
    price DOUBLE PRECISION NOT NULL,
    price_scaled DOUBLE PRECISION,
    product_age_days DOUBLE PRECISION,
    item_popularity_rank BIGINT NOT NULL,
    category_popularity_rank BIGINT NOT NULL,
    long_tail_flag BOOLEAN NOT NULL,
    cold_start_item_flag BOOLEAN NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (feature_batch_id, product_id)
);

CREATE TABLE IF NOT EXISTS recomart_features.user_item_features (
    feature_batch_id VARCHAR(80) NOT NULL,
    source_batch_id VARCHAR(100) NOT NULL,
    feature_reference_timestamp TIMESTAMPTZ NOT NULL,
    user_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    interaction_count BIGINT NOT NULL,
    view_count BIGINT NOT NULL,
    wishlist_count BIGINT NOT NULL,
    add_to_cart_count BIGINT NOT NULL,
    purchase_count BIGINT NOT NULL,
    implicit_score DOUBLE PRECISION NOT NULL,
    explicit_rating DOUBLE PRECISION,
    average_explicit_rating DOUBLE PRECISION,
    latest_explicit_rating DOUBLE PRECISION,
    total_quantity DOUBLE PRECISION NOT NULL,
    total_spend DOUBLE PRECISION NOT NULL,
    first_interaction_timestamp TIMESTAMPTZ NOT NULL,
    last_interaction_timestamp TIMESTAMPTZ NOT NULL,
    days_since_last_interaction DOUBLE PRECISION NOT NULL,
    first_purchase_timestamp TIMESTAMPTZ,
    last_purchase_timestamp TIMESTAMPTZ,
    days_since_last_purchase DOUBLE PRECISION,
    average_time_between_interactions_hours DOUBLE PRECISION,
    session_count BIGINT NOT NULL,
    user_item_view_to_cart_ratio DOUBLE PRECISION,
    user_item_cart_to_purchase_ratio DOUBLE PRECISION,
    user_category_affinity DOUBLE PRECISION NOT NULL,
    user_brand_affinity DOUBLE PRECISION NOT NULL,
    price_preference_distance DOUBLE PRECISION NOT NULL,
    price_preference_similarity DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (feature_batch_id, user_id, product_id)
);

CREATE TABLE IF NOT EXISTS recomart_features.item_cooccurrence_features (
    feature_batch_id VARCHAR(80) NOT NULL,
    source_batch_id VARCHAR(100) NOT NULL,
    feature_reference_timestamp TIMESTAMPTZ NOT NULL,
    item_id_a BIGINT NOT NULL,
    item_id_b BIGINT NOT NULL,
    cooccurrence_count BIGINT NOT NULL,
    cooccurring_user_count BIGINT NOT NULL,
    cooccurring_session_count BIGINT NOT NULL,
    co_purchase_count BIGINT NOT NULL,
    item_a_user_count BIGINT NOT NULL,
    item_b_user_count BIGINT NOT NULL,
    support DOUBLE PRECISION NOT NULL,
    confidence_a_to_b DOUBLE PRECISION NOT NULL,
    confidence_b_to_a DOUBLE PRECISION NOT NULL,
    lift DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    CHECK (item_id_a < item_id_b),
    PRIMARY KEY (feature_batch_id, item_id_a, item_id_b)
);

CREATE TABLE IF NOT EXISTS recomart_features.item_similarity_features (
    feature_batch_id VARCHAR(80) NOT NULL,
    source_batch_id VARCHAR(100) NOT NULL,
    feature_reference_timestamp TIMESTAMPTZ NOT NULL,
    product_id BIGINT NOT NULL,
    similar_product_id BIGINT NOT NULL,
    cosine_similarity DOUBLE PRECISION NOT NULL,
    jaccard_similarity DOUBLE PRECISION NOT NULL,
    category_similarity DOUBLE PRECISION NOT NULL,
    brand_similarity DOUBLE PRECISION NOT NULL,
    price_similarity DOUBLE PRECISION NOT NULL,
    rating_similarity DOUBLE PRECISION NOT NULL,
    combined_similarity_score DOUBLE PRECISION NOT NULL,
    similarity_rank BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    CHECK (product_id <> similar_product_id),
    PRIMARY KEY (feature_batch_id, product_id, similar_product_id)
);
